version: '3.9'
name: 'todo_list'

services:
  frontend:
    image: sermalenk/skypro-front:lesson-38
    restart: on-failure
    ports:
      - '80:80'
    depends_on:
      api:
        condition: service_started
      static:
        condition: service_completed_successfully
    volumes:
      - ../deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/

  postgres:
    image: postgres:15.1
    volumes:
      - ../db_data:/var/lib/postgresql/data
    env_file: .docker_env
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build: ../api/.
    env_file: .docker_env
    command: python3 manage.py migrate
    depends_on:
      postgres:
        condition: service_healthy

  static:
    build: ../api/.
    env_file: .docker_env
    command: python3 manage.py collectstatic -c --no-input
    volumes:
      - django_static:/code/static/

  api:
    build: ../api/.
    ports:
      - "8000:8000"
    env_file: .docker_env
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ../api:/code/

  bot:
    build: ../api/.
    env_file: .docker_env
    command: python3 manage.py runbot
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started

  redis:
    image: redis:latest
    restart: always
    env_file: .docker_env
    ports:
      - '6379:6379'
    volumes:
      - ../redis_data:/data
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_started


  celery:
    build: ../api/.
    env_file:
      - .docker_env
    command: celery -A todolist worker -l info
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      api:
        condition: service_started

volumes:
  django_static: