version: '3.9'

services:
  frontend:
    image: sermalenk/skypro-front:lesson-34
    volumes:
      - frontend:/app/build
    ports:
      - '8080:80'
    depends_on:
      - postgres
      - api

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data_todo_app:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    restart: always
    ports:
      - "5432:5433"

  api:
    image: bchkrvn/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: $SECRET_KEY
      DEBUG: 0
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: postgres
      DB_PORT: 5433
    tty: true
    command: bash -c "
      python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - postgres

volumes:
  postgres_data_todo_app:
  frontend: