# Generated by Django 4.2.2 on 2023-07-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_goal_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='goals',
            new_name='goal',
        ),
    ]
