# Generated by Django 4.2.2 on 2023-07-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_rename_goals_comment_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
