# Generated by Django 4.2.2 on 2023-07-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_alter_category_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardparticipant',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Владелец'), (2, 'Редактор'), (3, 'Читатель')], default=3, verbose_name='role'),
        ),
    ]
