# Generated by Django 4.2.2 on 2023-07-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='verification_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
