# Generated by Django 4.2.2 on 2023-07-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='verification_code',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
