# Generated by Django 4.2.2 on 2023-07-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_telegramuser_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='position',
            field=models.PositiveIntegerField(choices=[(1, 'Не авторизован'), (2, 'Ожидание команды'), (3, 'Выбор категории'), (4, 'Создание цели')], default=1),
        ),
    ]
