# Generated by Django 4.2.2 on 2023-07-20 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0015_alter_boardparticipant_role'),
        ('bot', '0004_telegramuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.category'),
        ),
    ]
