# Generated by Django 4.2.2 on 2023-07-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_telegramuser_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='tg_user_id',
        ),
    ]
