# Generated by Django 4.2.2 on 2023-07-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_telegramuser_tg_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='tg_chat_id',
            field=models.BigIntegerField(),
        ),
    ]
