version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data_todo_app:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: todo_list_app
      POSTGRES_PASSWORD: todo_list_app
      POSTGRES_DB: todo_list_app
    restart: always
    ports:
    - "5432:5432"

volumes:
  postgres_data_todo_app: